[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[theme]
base = "light"
primaryColor = "#1E90FF"
backgroundColor = "#F4F8FF"
secondaryBackgroundColor = "#E6F0FF"
textColor = "#002147"
font = "sans serif"
